import Foundation

/*
 * `lib/presentation/planner-copy.ts:317-616` の `ui.en` の逐語転記。キーの並びは `ui.ja` と
 * 同じ(`Copy.ja.keys == Copy.en.keys`)。
 */
extension Copy {
  public static let en = PlannerCopy(
    brandNote: { (place: String) -> String in place.isEmpty ? "Trip planner" : "\(place) trip planner" },
    destination: "Country",
    destinationSearch: "Type a country to choose",
    airportSearch: "Search airport, city or IATA code",
    noMatchingOption: "No matching option",
    optionCount: { (count: Int) -> String in "\(count) option\(count == 1 ? "" : "s")" },
    newTrip: "New trip",
    inputLabel: "Places you want to visit",
    sample: "Try a sample",
    swissDemo: "Swiss demo",
    parseHint: "Paste one per line, or use commas, slashes and middle dots; we separate the places. Day headings, times, booked / must / optional and stay length are also read. Local-language names are fine.",
    previewHeading: { (count: Int) -> String in "Read as \(count) place\(count == 1 ? "" : "s")" },
    previewFormat: "Make one per line",
    previewDay: { (day: Int) -> String in "Day \(day)" },
    previewUnparsed: "Can't read this line as a place",
    previewStay: { (minutes: Int) -> String in "Stay \(minutes) min" },
    days: "Days",
    date: "First day",
    hotel: "Hotel or preferred area",
    hotelPlaceholder: "e.g. near the main station (optional)",
    arrival: "Arrival airport",
    arrivalTime: "Arrival time",
    departure: "Departure airport",
    departureTime: "Departure time",
    pace: "Pace",
    travelHeading: "Getting around",
    travelAuto: "Recommended · efficient",
    travelCar: "Rental car",
    moveCar: "Drive",
    timebandHeading: "Day rhythm",
    timebandEarly: "Early 8:00",
    timebandNormal: "Standard 9:00",
    timebandLate: "Slow 10:30",
    dayEndHeading: "Day ends by",
    dayEndNone: "Standard 22:00",
    curfewOver: { (time: String) -> String in "Runs past your \(time) target" },
    recentHeading: "Recent trips",
    recentNote: "Stored only on this device",
    recentDays: { (days: Int) -> String in "\(days) days" },
    recentDelete: "Remove",
    moveDay: "Move to day",
    mealChoose: "Pick this place",
    mealChosen: "Added to the day",
    toastAdded: "Added to the itinerary",
    share: "Copy share link",
    shareCopied: "Copied",
    shareTitle: "Copies a link that reopens this trip with the same inputs. Everything lives in the link itself; nothing is stored.",
    relaxed: "Relaxed",
    balanced: "Balanced",
    fast: "See more",
    buildingTitle: "Building your trip",
    buildingBody: "We confirm places, hours and the base, then calculate a plan that keeps every hard constraint.",
    buildingBodyNoSocial: "We confirm places, hours and the base, then calculate every hard constraint. Route data blends in after the result appears.",
    buildingCancel: "Back to input",
    buildSteps: PlannerCopy.BuildSteps(grouping: "Grouping nearby places into days", ordering: "Finding a practical order", enriching: "Finding a practical base and meal stops"),
    mapReady: "Google Maps",
    mapEmpty: "Your trip will appear here",
    legendLabel: "Legend",
    legendMeasured: "measured",
    legendEstimated: "estimated",
    legendAnchor: "planned stop",
    legendSuggestion: "suggestion",
    routeIdeasChip: "Near today's plan",
    routeIdeasTitle: "Worthwhile places near today's plan",
    routeIdeasSubtitle: "We searched around today's live route and planned stops, then kept only places backed by ratings.",
    routeIdeasLoading: "Finding worthwhile stops along this route…",
    routeIdeasUnavailable: "Route ideas are unavailable right now. Your plan still works as-is.",
    routeIdeasRateLimited: "Today's free search allowance has been used. Your plan still works as-is.",
    routeIdeasEmpty: "Nothing met both the rating and proximity bar, so we did not pad the day with a weak suggestion.",
    routeIdeasDistance: { (meters: Int) -> String in meters < 1_000 ? "About \(meters)m from the route" : "About \(PlannerCopy.fixed1(Double(meters) / 1_000))km from the route" },
    routeIdeasAdd: "Add to this day & reroute",
    routeIdeasAdded: "Already added",
    routeIdeasNote: "Ratings are from Google Maps. Proximity is an approximate distance from available Google route geometry, falling back to planned stops for any missing leg. TripCheck reroutes after you add one; nothing is added automatically.",
    edit: "Back to input",
    openMaps: "Open in Google Maps",
    removeStop: "Remove from the plan",
    removedHeading: "Removed by you",
    restoreStop: "Put back",
    backToPlan: "Back to your plan",
    hotelDepartRow: { (mode: String, minutes: Int) -> String in "From hotel · \(mode) ~\(minutes) min" },
    hotelReturnRow: { (mode: String, minutes: Int) -> String in "To hotel · \(mode) ~\(minutes) min" },
    travelTotal: { (minutes: Int) -> String in "~\(minutes) min total travel" },
    precipitation: { (percent: Int) -> String in "\(percent)% rain" },
    forecastNote: "Open-Meteo forecast",
    holidayBadge: "PH",
    holidayNote: { (name: String) -> String in "Public holiday “\(name)” — museums and shops may close or shorten hours; re-check opening times" },
    holidayRegional: " (some regions only)",
    sundayClosingNote: "Sunday — most shops and supermarkets are closed by law (station shops are the usual exception)",
    flightKindHeading: "Flight type",
    flightInternational: "International",
    flightDomestic: "Domestic",
    essentialsPlug: "Power plug",
    essentialsEmergency: "Emergency",
    essentialsEntry: "Entry (Japan passport)",
    essentialsPass: "Transit pass",
    essentialsOfficial: "Official info",
    beforeStrike: "Strike / disruption check",
    beforeMedication: "Medication rules",
    beforeMedicationNote: "Carry medicines in their original packaging with documentation. Some countries require advance permits for psychotropic ingredients or large quantities; the US can confiscate non-FDA-approved drugs even with a prescription.",
    beforeHeading: "Before you go",
    beforeOverdue: "Action needed",
    beforeDueSoon: "Due soon",
    beforePassportLabel: "Passport expiry date",
    beforePassportHint: "Used for the validity check. Stored on this device only.",
    passportCountry: "Passport country",
    passportUnset: "Not set (hide personalised entry checks)",
    passportJapan: "Japan",
    passportOther: "Other",
    passportUnsupported: "Personalised entry checks currently support Japanese passports only. For other passports, use the destination's official guidance.",
    beforeBooked: "Planned as booked — check your voucher and entry method",
    beforeBookedAt: { (time: String) -> String in "Planned as booked for \(time) — check your voucher and entry method" },
    beforeWatch: "Sell-outs or queues reported — consider booking ahead or going first thing",
    print: "Print / PDF",
    printTitle: "Print or save the whole trip as one page (for offline use)",
    printBooked: "booked",
    printFooter: "Times are planning estimates. Reconfirm travel and opening hours locally. · Weather by Open-Meteo",
    legModes: "Travel mode for this leg. Tap to pin, tap again for automatic",
    move: PlannerCopy.MoveLabels(walk: "Walk", transit: "Train", taxi: "Taxi"),
    minutes: { (value: Int) -> String in "\(value) min" },
    legLive: "Google route",
    unknown: "Not shown on the map",
    placeFallback: "Some places could not be found. The plan uses only the ones we could confirm.",
    noDays: "Nothing could be placed on the map yet. A slightly different name often helps.",
    openDay: "Nothing planned for this day yet",
    selectHint: "Tap a pin or a stop to open details",
    mealIdeas: "Best fit for this route",
    gapRecoLabel: { (minutes: Int) -> String in "Fits your \(minutes)-minute gap" },
    recoAccept: "Add this",
    recoAlternatives: "See alternatives",
    detourLine: { (minutes: Int) -> String in "~\(minutes) min from the route" },
    lunchChip: "Lunch",
    dinnerChip: "Dinner",
    foodLoading: "Finding nearby places…",
    foodUnavailable: "Places did not load. Open the same search in Google Maps instead.",
    maps: "View on map",
    foodNote: "Ranked by Google rating strength, review volume, distance and open status. Public social evidence is shown only when a cited page was found.",
    foodFresh: { (count: Int) -> String in "\(count) recent public signals" },
    hotelChip: "Change base",
    hotelPending: "Finding a base…",
    hotelCandidate: "Recommended base",
    hotelSavesTravel: { (minutes: Int) -> String in
      let hours = Int((Double(minutes) / 60).rounded(.down))
      let rest = minutes % 60
      let duration = hours > 0 ? "\(hours)h\(rest > 0 ? " \(rest)m" : "")" : "\(rest)m"
      return "Saves \(duration) of travel"
    },
    hotelNoAvailability: "Confirm price and availability with a booking provider.",
    hotelUnavailable: "Hotel options didn't load.",
    hotelSearch: "Search hotels on Google Maps",
    hotelRefresh: "Search hotels again",
    hotelRefreshChanged: "Re-search for the changed itinerary",
    hotelRefreshing: "Searching for a better base…",
    hotelRefreshHint: "Your destinations changed, so the hotel options can be updated too.",
    hotelRefreshFailed: "The re-search failed. Your current hotel has been kept.",
    stayModeHeading: "Stay style",
    staySame: "One hotel",
    stayNightly: "Change nightly",
    nightLabel: { (night: Int) -> String in "Night \(night)" },
    nightlyLoading: "Finding hotels for each night…",
    nightlyUnavailable: "Nightly options didn't load. The plan keeps one hotel.",
    nightlyNightMissing: "No option loaded for this night — the shared hotel stays.",
    styleRecommended: "Best match",
    styleLuxury: "Luxury",
    styleNote: "Reference prices are dateless and availability is unknown, so they do not determine a value winner.",
    hotelRankNote: "Every day gets one equal vote. Hotels with a lower average and worst-day straight-line distance rank higher, then Google rating and review strength are added. Confirm actual travel time on the mapped routes.",
    hotelCompareHeading: "Compare picks — tap to switch",
    priceUnlisted: "No listed price",
    rakutenTag: { (average: Double, count: Int) -> String in "Rakuten Travel ★\(PlannerCopy.fixed1(average)) (\(PlannerCopy.grouped(count)))" },
    hotelPriceNote: "¥ prices are Rakuten Travel's reference minimum (dateless).",
    hotelReasonTop: "Top combined score for whole-trip access, rating and review strength.",
    hotelReasonNearest: "Lowest distance burden across each day's destinations.",
    hotelReasonRated: "Highest Google rating among candidates backed by at least 50 reviews.",
    hotelReasonValue: "A reference price is shown, but TripCheck does not call it best value without dated availability.",
    hotelReasonSpecified: "This matches the hotel you entered and is also used as the route's start and end base.",
    hotelReasonPicked: "Your pick from the alternatives.",
    hotelPurposeHeading: "What matters most?",
    hotelPurposeBalanced: "Overall",
    hotelPurposeNearest: "Less travel",
    hotelPurposeRated: "Top rated",
    hotelPurposeHelp: "Compare total travel and rating here; confirm price and availability with a booking provider.",
    axisOverall: "Overall pick",
    axisNearest: "Least travel",
    axisTopRated: "Top rated",
    distanceFrom: { (distance: String) -> String in "~\(distance) straight-line average" },
    hotelWideTrip: "Your destinations cover a wide area. One hotel still leaves a long travel day; changing hotels nightly will be easier.",
    useThisHotel: "Switch to this hotel",
    tonightHotel: { (name: String) -> String in "Tonight · \(name)" },
    publicSources: "Public social and article sources",
    reservation: "Booked",
    timePinned: "Timed",
    lateBy: { (minutes: Int) -> String in "Runs about \(minutes) min past the set time" },
    lateShort: { (minutes: Int) -> String in "\(minutes) min late" },
    must: "Must",
    optional: "Optional",
    stayLabel: "Stay",
    stayAuto: "Auto",
    dayStart: "Start time",
    dayEnd: "End time",
    dayTabsLabel: "Choose a day",
    dayTimelineLabel: { (day: String) -> String in "\(day) itinerary" },
    dayBreakdownLabel: "Day time breakdown",
    dayWindowLabel: "Day window",
    dayPlannedLabel: "Planned",
    dayAvailableLabel: "Available",
    dayTravelLabel: "Travel",
    estimated: "Travel time is estimated",
    estimatedDetail: "Legs update automatically only where Google Maps route data is available.",
    checkHours: "Check opening hours before you go",
    betaRegion: "Beta coverage in this region",
    scopeBorder: "This trip crosses a national border, so accuracy drops. Confirm cross-border legs on official sites.",
    scopeTimezone: "This trip spans more than one time zone. Confirm each time in the local zone.",
    scopeFerry: "Ferry legs are outside TripCheck's scope. Confirm sailing times on the official site.",
    shareWarning: "Anyone with the full link can view this trip",
    shareWarningDetail: "The link itself contains the trip data. Recipients, browser history and extensions can read it. Do not post it publicly.",
    sheetExpand: "Expand sheet",
    sheetShrink: "Back to half height",
    sheetMinimize: "Minimize sheet",
    sheetPeekOpen: "Open the sheet",
    openingAdjusted: "Timed to verified opening hours",
    openingConflict: "Recheck opening hours and booking time",
    openingClosedDay: "Likely closed this day — consider moving it",
    excludedHeading: "Left out of this plan",
    excludedClosed: "closed or hours don't fit",
    excludedPace: "optional stop beyond this pace",
    overCapacity: "Some days hold more than this pace fits. Add a day or trim optional stops.",
    fitSelectedDays: "Change days and recalculate",
    fitDaysValue: { (days: Int) -> String in "\(days) day\(days == 1 ? "" : "s")" },
    fitDaysDecrease: "Make this trip one day shorter",
    fitDaysIncrease: "Add one day to this trip",
    walkingSafety: "Walking routes are beta. Check real-world safety conditions.",
    deadlineOver: { (time: String) -> String in "Runs past the \(time) airport cutoff" },
    language: "Language",
    privacy: "Your recent plans stay on this device",
    privacyTitle: "No account needed · Your recent plans stay on this device · Privacy policy",
    resolveRemove: "Remove",
    resolveRemoveAria: { (name: String) -> String in "Remove “\(name)” from the list" },
    manualAddressResolving: "Checking that address…",
    manualAddressNotFound: "We couldn't find that address",
    fieldCheck: "Check recent public sources too",
    fieldChecking: "Checking…",
    fieldChecked: "Public sources checked",
    fieldRetry: "Try again",
    fieldUnavailable: "Live info did not load. Recheck the official source before you go.",
    fieldEvidence: "On-the-ground signals",
    openNow: "Listed open now",
    plannedOpen: "Open for this meal time",
    closedNow: "Listed closed now",
    hoursUnknown: "Hours unknown",
    dayHours: { (value: String) -> String in "Hours this day: \(value)" },
    dayClosed: "Listed closed on this day",
    cashOnly: "Cash only",
    cardsAccepted: "Cards accepted",
    noWebsite: "No official site",
    photoLabel: "Photo:",
    recentVoices: "Recent reviews — real voices",
    freshHeading: "Latest public signals",
    freshLoading: "Searching public sources…",
    freshEmpty: "No public source could be verified as updated within 90 days. Undated pages are not presented as recent.",
    freshUnavailable: "Fresh sources are unavailable right now. Recheck Google Maps and the official source.",
    freshPaused: "Public social checks are paused for now. Showing Google hours and reviews only.",
    freshSource: PlannerCopy.FreshSourceLabels(social: "Social", news: "News", blog: "Firsthand", web: "Web"),
    freshAgeUnknown: "Date unknown",
    freshAiRole: "Claude searches and summarizes public posts only — private or login-only posts can't be read. Schedule and routing stay rule-based.",
    official: "Official site",
    latestX: "Latest on X",
    instagram: "Search Instagram",
    aiAudited: "Evidence summarized by Claude",
    rulesAudited: "Evidence organized automatically",
    crowd: PlannerCopy.CrowdLabels(quiet: "Quiet", moderate: "Steady", busy: "Busy", veryBusy: "Very busy"),
    crowdWeekend: " · weekend",
    crowdForecast: " · forecast",
    close: "Close",
  )
}
