import Foundation

/*
 * `lib/presentation/planner-copy.ts:19-316` の `ui.ja` の逐語転記。
 *
 * 括弧・約物(「」、（）、·、—、〜)は TS のバイトそのまま。順番も TS の並びのまま —— この
 * 並びが `PlannerCopy.keys` になり、`Copy.en` のキー列と一致することがテストの前提。
 */
extension Copy {
  public static let ja = PlannerCopy(
    brandNote: { (place: String) -> String in place.isEmpty ? "旅のプランナー" : "\(place)の旅プランナー" },
    destination: "行き先の国",
    destinationSearch: "国名を入力して選択",
    airportSearch: "空港名・都市・3レターコードで検索",
    noMatchingOption: "一致する候補がありません",
    optionCount: { (count: Int) -> String in "\(count)件の候補" },
    newTrip: "新しい旅",
    inputLabel: "行きたい場所",
    sample: "サンプルを見る",
    swissDemo: "スイスデモ",
    parseHint: "改行のほか「・」「／」「,」でまとめて貼っても、場所ごとに分けます。「1日目」、時刻、予約、必須、滞在時間も読み取ります。地名は現地表記でも英語でも大丈夫です。",
    previewHeading: { (count: Int) -> String in "\(count)か所として読み取り" },
    previewFormat: "1件ずつに整える",
    previewDay: { (day: Int) -> String in "\(day)日目" },
    previewUnparsed: "場所名として読み取れない行",
    previewStay: { (minutes: Int) -> String in "滞在\(minutes)分" },
    days: "日数",
    date: "初日",
    hotel: "ホテル名・泊まりたいエリア",
    hotelPlaceholder: "例：中央駅の近く（未定でもOK）",
    arrival: "到着空港",
    arrivalTime: "到着時刻",
    departure: "出発空港",
    departureTime: "出発時刻",
    pace: "旅のペース",
    travelHeading: "移動手段",
    travelAuto: "おまかせ（効率重視）",
    travelCar: "レンタカー・車",
    moveCar: "車",
    timebandHeading: "1日の時間帯",
    timebandEarly: "朝型 8:00〜",
    timebandNormal: "標準 9:00〜",
    timebandLate: "ゆっくり 10:30〜",
    dayEndHeading: "1日の終わり",
    dayEndNone: "標準 22:00",
    curfewOver: { (time: String) -> String in "\(time) までに収まっていません" },
    recentHeading: "最近の旅程",
    recentNote: "この端末の中だけに保存されます",
    recentDays: { (days: Int) -> String in "\(days)日間" },
    recentDelete: "削除",
    moveDay: "日を移動",
    mealChoose: "この店にする",
    mealChosen: "行程に入れました",
    toastAdded: "旅程に追加しました",
    share: "共有リンク",
    shareCopied: "コピーしました",
    shareTitle: "この旅程を同じ設定で開けるリンクをコピーします。内容はリンクの中だけに入り、サーバには保存されません。",
    relaxed: "ゆったり",
    balanced: "標準",
    fast: "たくさん回る",
    buildingTitle: "予定をつくっています",
    buildingBody: "場所・営業時間・拠点を確認し、固定条件を破らない予定を計算します。",
    buildingBodyNoSocial: "場所・営業時間・拠点を確認し、固定条件を破らない予定を計算します。経路データは表示後に反映します。",
    buildingCancel: "入力にもどる",
    buildSteps: PlannerCopy.BuildSteps(grouping: "近い場所を同じ日にまとめています", ordering: "回る順番を整えています", enriching: "ホテルと食事の候補を探しています"),
    mapReady: "Googleマップ",
    mapEmpty: "行き先を入れると、ここに旅が描かれます",
    legendLabel: "凡例",
    legendMeasured: "実経路",
    legendEstimated: "推定",
    legendAnchor: "予定地点",
    legendSuggestion: "おすすめ地点",
    routeIdeasChip: "今日の予定の近く",
    routeIdeasTitle: "今日の予定の近くなら、ここも寄れます",
    routeIdeasSubtitle: "今日の実経路と予定地点の周辺から、評価の裏付けがある場所だけを探しました。",
    routeIdeasLoading: "動線上の候補を探しています…",
    routeIdeasUnavailable: "いまは動線上の候補を取得できませんでした。予定そのものはそのまま使えます。",
    routeIdeasRateLimited: "今日の無料検索枠に達しました。予定そのものはそのまま使えます。",
    routeIdeasEmpty: "評価と近さの両方を満たす候補は見つかりませんでした。無理に場所を足していません。",
    routeIdeasDistance: { (meters: Int) -> String in meters < 1_000 ? "予定経路から約\(meters)m" : "予定経路から約\(PlannerCopy.fixed1(Double(meters) / 1_000))km" },
    routeIdeasAdd: "この日に追加して再計算",
    routeIdeasAdded: "追加済み",
    routeIdeasNote: "評価はGoogle Maps、近さは取得できたGoogle実経路（未取得区間は予定地点）への概算距離です。追加後の順番と移動時間はTripCheckが再計算します。自動では追加しません。",
    edit: "入力にもどる",
    openMaps: "Google Mapsで開く",
    removeStop: "この行き先を予定から外す",
    removedHeading: "自分で外した場所",
    restoreStop: "もどす",
    backToPlan: "作成した計画にもどる",
    hotelDepartRow: { (mode: String, minutes: Int) -> String in "ホテルから \(mode) 約\(minutes)分" },
    hotelReturnRow: { (mode: String, minutes: Int) -> String in "ホテルへ \(mode) 約\(minutes)分" },
    travelTotal: { (minutes: Int) -> String in "移動 合計約\(minutes)分" },
    precipitation: { (percent: Int) -> String in "降水\(percent)%" },
    forecastNote: "Open-Meteo予報",
    holidayBadge: "祝",
    holidayNote: { (name: String) -> String in "祝日「\(name)」— 美術館・商店は休業・短縮営業の可能性。営業時間の再確認を" },
    holidayRegional: "（一部地域のみ）",
    sundayClosingNote: "日曜 — 閉店法で商店・スーパーはほぼ休業（駅ナカ店舗は例外が多い）",
    flightKindHeading: "フライトの種類",
    flightInternational: "国際線",
    flightDomestic: "国内線",
    essentialsPlug: "電源プラグ",
    essentialsEmergency: "緊急通報",
    essentialsEntry: "入国（日本のパスポート）",
    essentialsPass: "交通パス",
    essentialsOfficial: "公式情報",
    beforeStrike: "スト・運休の確認",
    beforeMedication: "薬の持ち込み",
    beforeMedicationNote: "常用薬は元の箱・説明書きのまま携行（一包化は中身不明扱いのリスク）。向精神薬成分や多量の持込みは事前手続きが必要な国がある。米国はFDA未認可薬だと処方箋があっても没収されることがある。",
    beforeHeading: "出発前チェック",
    beforeOverdue: "要対応",
    beforeDueSoon: "期限接近",
    beforePassportLabel: "パスポートの有効期限",
    beforePassportHint: "残存期間チェック用。この端末にのみ保存されます。",
    passportCountry: "パスポートの国",
    passportUnset: "未選択（入国判定を表示しない）",
    passportJapan: "日本",
    passportOther: "その他",
    passportUnsupported: "現在の個別入国判定は日本のパスポートのみ対応。その他は目的地の公式情報を確認してください。",
    beforeBooked: "予約済みとして計画 — バウチャーと入場方法を確認",
    beforeBookedAt: { (time: String) -> String in "\(time)に予約済みとして計画 — バウチャーと入場方法を確認" },
    beforeWatch: "売り切れ・行列の報告あり — 事前予約か朝イチを検討",
    print: "印刷 / PDF",
    printTitle: "全日程を1枚にして印刷・PDF保存（オフライン用）",
    printBooked: "予約",
    printFooter: "時間は計画用の目安です。移動と営業時間は現地で最終確認してください。 · Weather by Open-Meteo",
    legModes: "この区間の移動手段。タップで固定、もう一度タップで自動に戻す",
    move: PlannerCopy.MoveLabels(walk: "徒歩", transit: "電車", taxi: "タクシー"),
    minutes: { (value: Int) -> String in "\(value)分" },
    legLive: "Google Maps経路",
    unknown: "地図に出せなかった場所",
    placeFallback: "見つからなかった場所があります。確認できた場所だけで組み立てています。",
    noDays: "地図に置ける場所がまだありません。名前を少し変えると見つかることがあります。",
    openDay: "この日はまだ予定がありません",
    selectHint: "ピンや行き先をタップすると、詳しい情報が開きます",
    mealIdeas: "この動線なら、ここが便利です",
    gapRecoLabel: { (minutes: Int) -> String in "\(minutes)分の空き時間に寄れます" },
    recoAccept: "ここにする",
    recoAlternatives: "他を見る",
    detourLine: { (minutes: Int) -> String in "動線から約\(minutes)分" },
    lunchChip: "昼ごはん",
    dinnerChip: "夜ごはん",
    foodLoading: "近くのお店を探しています…",
    foodUnavailable: "お店を取得できませんでした。Google Mapsで同じ条件を開けます。",
    maps: "地図で見る",
    foodNote: "Googleの評価・口コミ量・距離・営業表示をロジックで比較。公開SNSは引用できた情報だけを補足しています。",
    foodFresh: { (count: Int) -> String in "最近の公開情報 \(count)件" },
    hotelChip: "ホテルを変える",
    hotelPending: "ホテルを探しています…",
    hotelCandidate: "おすすめの拠点",
    hotelSavesTravel: { (minutes: Int) -> String in
      let hours = Int((Double(minutes) / 60).rounded(.down))
      let rest = minutes % 60
      let duration = hours > 0 ? "\(hours)時間\(rest > 0 ? "\(rest)分" : "")" : "\(rest)分"
      return "移動を\(duration)短縮"
    },
    hotelNoAvailability: "料金・空室は宿泊サイトで最終確認してください。",
    hotelUnavailable: "ホテル候補を取得できませんでした。",
    hotelSearch: "Google Mapsでホテルを探す",
    hotelRefresh: "ホテルを再検索",
    hotelRefreshChanged: "変更後の行程でホテルを再検索",
    hotelRefreshing: "ホテルを探し直しています…",
    hotelRefreshHint: "行き先が変わったため、ホテル候補も更新できます。",
    hotelRefreshFailed: "再検索できませんでした。今のホテルはそのまま残しています。",
    stayModeHeading: "泊まり方",
    staySame: "同じホテルで通す",
    stayNightly: "日ごとに変える",
    nightLabel: { (night: Int) -> String in "\(night)泊目" },
    nightlyLoading: "夜ごとの候補を探しています…",
    nightlyUnavailable: "日ごとの候補を取得できませんでした。共通のホテルのまま計画しています。",
    nightlyNightMissing: "この夜は候補を取得できず、共通のホテルのままです。",
    styleRecommended: "おすすめ",
    styleLuxury: "ラグジュアリー",
    styleNote: "参考価格は日付・空室未指定のため、コスパ順位には使いません。",
    hotelRankNote: "各日の行き先を1日1票で比較し、直線距離の平均と最も遠い日の負担が小さいホテルを優先。そこへGoogle評価と口コミ量を加えて総合順位を決めます。実際の所要時間は地図の経路で確認します。",
    hotelCompareHeading: "候補を比べる（タップで切り替え）",
    priceUnlisted: "価格未掲載",
    rakutenTag: { (average: Double, count: Int) -> String in "楽天トラベル ★\(PlannerCopy.fixed1(average))（\(PlannerCopy.grouped(count))件）" },
    hotelPriceNote: "¥価格は楽天トラベル掲載の参考最安（日付未指定）です。",
    hotelReasonTop: "全日程への行きやすさ・評価・口コミ量の合計で1位の候補です。",
    hotelReasonNearest: "各日の行き先への距離負担が最も小さい候補です。",
    hotelReasonRated: "十分な口コミ数がある候補の中で、Google評価が最も高いホテルです。",
    hotelReasonValue: "参考価格は表示しますが、日付と空室が未確認のためコスパ1位とは判定しません。",
    hotelReasonSpecified: "入力したホテル名に一致した候補です。行程の出発・帰着地点にも反映しています。",
    hotelReasonPicked: "切り替えて選んだ候補です。",
    hotelPurposeHeading: "何を優先する？",
    hotelPurposeBalanced: "総合",
    hotelPurposeNearest: "移動を少なく",
    hotelPurposeRated: "評価重視",
    hotelPurposeHelp: "総移動時間と評価を比較します。価格・空室は予約サイトで確認してください。",
    axisOverall: "総合おすすめ",
    axisNearest: "移動が少ない",
    axisTopRated: "口コミ高評価",
    distanceFrom: { (distance: String) -> String in "各日の中心へ直線平均約\(distance)" },
    hotelWideTrip: "行き先が広範囲です。1つのホテルでは長距離移動が残るため、日ごとに変える方が楽です。",
    useThisHotel: "このホテルに切り替え",
    tonightHotel: { (name: String) -> String in "今夜の宿 · \(name)" },
    publicSources: "公開SNS・記事の出典",
    reservation: "予約",
    timePinned: "時間指定",
    lateBy: { (minutes: Int) -> String in "指定時刻に約\(minutes)分間に合わない見込み" },
    lateShort: { (minutes: Int) -> String in "\(minutes)分遅れ" },
    must: "必須",
    optional: "任意",
    stayLabel: "滞在時間",
    stayAuto: "自動",
    dayStart: "開始時刻",
    dayEnd: "終了時刻",
    dayTabsLabel: "日程を選ぶ",
    dayTimelineLabel: { (day: String) -> String in "\(day)の行程" },
    dayBreakdownLabel: "この日の時間内訳",
    dayWindowLabel: "時間帯",
    dayPlannedLabel: "予定",
    dayAvailableLabel: "利用可能",
    dayTravelLabel: "移動",
    estimated: "所要時間は目安です",
    estimatedDetail: "Google Maps経路データを取得できた区間だけ自動で更新します。",
    checkHours: "出発前に営業時間を確認",
    betaRegion: "この地域はベータ対応です",
    scopeBorder: "国をまたぐ旅程は精度が下がります。国境をまたぐ移動は公式サイトで確認してください。",
    scopeTimezone: "複数の時間帯にまたがる旅程です。時刻は各地の現地時間で確認してください。",
    scopeFerry: "フェリー区間は対応範囲外です。運航時刻は公式サイトで確認してください。",
    shareWarning: "リンクを知っている人は旅程を見られます",
    shareWarningDetail: "このリンク自体が旅程データです。受信者、ブラウザ履歴、拡張機能から読めます。公開場所へ貼らないでください。",
    sheetExpand: "シートを全画面に広げる",
    sheetShrink: "シートを半分の高さに戻す",
    sheetMinimize: "シートを最小化",
    sheetPeekOpen: "シートを開く",
    openingAdjusted: "営業時間に合わせて訪問時刻を調整",
    openingConflict: "営業時間と予約時刻を再確認",
    openingClosedDay: "この日は休業の可能性 — 日の移動を検討",
    excludedHeading: "予定から外した場所",
    excludedClosed: "休業・営業時間が合わない",
    excludedPace: "ペースに収まらない任意の場所",
    overCapacity: "1日に収まりきらない日があります。日数を増やすか、任意の場所を減らすと現実的になります。",
    fitSelectedDays: "日数を変えて再計算",
    fitDaysValue: { (days: Int) -> String in "\(days)日間" },
    fitDaysDecrease: "旅行を1日短くする",
    fitDaysIncrease: "旅行を1日長くする",
    walkingSafety: "徒歩経路はベータ版。安全状況は現地で確認してください。",
    deadlineOver: { (time: String) -> String in "空港へ向かう目安 \(time) を超えています" },
    language: "言語",
    privacy: "旅程はこの端末に保存されます",
    privacyTitle: "アカウント不要 · プライバシー方針",
    resolveRemove: "外す",
    resolveRemoveAria: { (name: String) -> String in "「\(name)」をリストから外す" },
    manualAddressResolving: "住所を確認しています…",
    manualAddressNotFound: "住所を見つけられませんでした",
    fieldCheck: "最新の公開情報も確認",
    fieldChecking: "確認中…",
    fieldChecked: "公開情報も確認済み",
    fieldRetry: "再試行",
    fieldUnavailable: "現地情報を取得できませんでした。出発前に公式情報の確認を。",
    fieldEvidence: "いまの現地シグナル",
    openNow: "営業中の表示",
    plannedOpen: "食事時間に営業予定",
    closedNow: "営業時間外の表示",
    hoursUnknown: "営業時間は不明",
    dayHours: { (value: String) -> String in "この日の営業 \(value)" },
    dayClosed: "この日は休業の表示",
    cashOnly: "現金のみ",
    cardsAccepted: "カード可",
    noWebsite: "公式サイト未掲載",
    photoLabel: "写真:",
    recentVoices: "最近の口コミ（生の声）",
    freshHeading: "ネットの近況",
    freshLoading: "公開情報を探しています…",
    freshEmpty: "90日以内と確認できる公開情報は見つかりませんでした。日付不明の情報も無理に最新扱いしません。",
    freshUnavailable: "いまは最新情報を確認できませんでした。Google Mapsや公式情報も確認してください。",
    freshPaused: "公開SNSチェックはいま休止中です。Googleの営業情報・口コミだけで表示しています。",
    freshSource: PlannerCopy.FreshSourceLabels(social: "SNS", news: "ニュース", blog: "体験記", web: "公開情報"),
    freshAgeUnknown: "更新日不明",
    freshAiRole: "Claudeが公開の投稿・記事だけを検索して要約します（非公開・ログイン限定の投稿は対象外）。日程と移動はルール計算です。",
    official: "公式サイト",
    latestX: "Xで最新の声",
    instagram: "Instagramで探す",
    aiAudited: "Claudeが根拠だけを要約",
    rulesAudited: "取得情報を自動整理",
    crowd: PlannerCopy.CrowdLabels(quiet: "静かめ", moderate: "ふつう", busy: "混みやすい", veryBusy: "かなり混む"),
    crowdWeekend: "・週末",
    crowdForecast: "（予測）",
    close: "閉じる",
  )
}
