/// TS `destinationList` (`lib/destinations.ts:131-929`) — 25 profiles, transcribed verbatim
/// (numbers, URLs, English/Japanese copy unchanged). `ko`/`zh` names present in the TS
/// object literals are dropped: `PlannerLocale` is ja/en only.

/// TS `const hour = (h, m = 0) => h * 60 + m;` (`lib/destinations.ts:131`)
private func hour(_ h: Int, _ m: Int = 0) -> Int { h * 60 + m }

/* ── Airports ─────────────────────────────────────────────────────────────
 * Main international gateways only. A traveller flying into a smaller field
 * leaves the airport fields empty and loses nothing but the arrival/departure
 * squeeze on the first and last day.
 */


private let japanAirports: [DestinationAirport] = [
  DestinationAirport(code: "HND", names: [.en: "Haneda", .ja: "羽田空港"], latitude: 35.5494, longitude: 139.7798, transferMinutes: 60, internationalDepartureMinutes: 180, sourceUrl: "https://www.tokyo-haneda.com/en/flight/detail/int_departure.html"),
  DestinationAirport(code: "NRT", names: [.en: "Narita", .ja: "成田空港"], latitude: 35.772, longitude: 140.3929, transferMinutes: 105, internationalDepartureMinutes: 120, sourceUrl: "https://www.narita-airport.jp/en/airportguide/inter-dep/"),
  DestinationAirport(code: "KIX", names: [.en: "Kansai", .ja: "関西国際空港"], latitude: 34.432, longitude: 135.2304, transferMinutes: 60, internationalDepartureMinutes: 150, sourceUrl: "https://www.kansai-airport.or.jp/en/"),
  DestinationAirport(code: "ITM", names: [.en: "Itami", .ja: "大阪国際空港（伊丹）"], latitude: 34.7855, longitude: 135.4382, transferMinutes: 40, internationalDepartureMinutes: 120, sourceUrl: "https://www.osaka-airport.co.jp/en/"),
  DestinationAirport(code: "NGO", names: [.en: "Chubu Centrair", .ja: "中部国際空港"], latitude: 34.8584, longitude: 136.8054, transferMinutes: 50, internationalDepartureMinutes: 150, sourceUrl: "https://www.centrair.jp/en/"),
  DestinationAirport(code: "FUK", names: [.en: "Fukuoka", .ja: "福岡空港"], latitude: 33.5859, longitude: 130.4507, transferMinutes: 20, internationalDepartureMinutes: 150, sourceUrl: "https://www.fukuoka-airport.jp/en/"),
  DestinationAirport(code: "CTS", names: [.en: "New Chitose", .ja: "新千歳空港"], latitude: 42.7752, longitude: 141.6923, transferMinutes: 50, internationalDepartureMinutes: 150, sourceUrl: "https://www.hokkaido-airports.com/en/new-chitose/"),
  DestinationAirport(code: "OKA", names: [.en: "Naha", .ja: "那覇空港"], latitude: 26.1958, longitude: 127.6458, transferMinutes: 25, internationalDepartureMinutes: 150, sourceUrl: "https://www.naha-airport.co.jp/en/"),
]

private let swissAirports: [DestinationAirport] = [
  DestinationAirport(code: "ZRH", names: [.en: "Zurich", .ja: "チューリッヒ空港"], latitude: 47.4647, longitude: 8.5492, transferMinutes: 25, internationalDepartureMinutes: 150, sourceUrl: "https://www.flughafen-zuerich.ch/en/passengers"),
  DestinationAirport(code: "GVA", names: [.en: "Geneva", .ja: "ジュネーブ空港"], latitude: 46.2381, longitude: 6.1089, transferMinutes: 20, internationalDepartureMinutes: 150, sourceUrl: "https://www.gva.ch/en/"),
  DestinationAirport(code: "BSL", names: [.en: "Basel EuroAirport", .ja: "バーゼル空港"], latitude: 47.5896, longitude: 7.5299, transferMinutes: 30, internationalDepartureMinutes: 150, sourceUrl: "https://www.euroairport.com/en/"),
]

/// Airport pairs that genuinely serve the same metropolitan base (TS `airportMetroGroups`,
/// `lib/destinations.ts:151-160`). Country profiles also contain gateways for entirely
/// different cities, so their full airport list must never be presented as interchangeable
/// options.
let airportMetroGroups: [[String]] = [
  ["HND", "NRT"],
  ["KIX", "ITM"],
  ["ICN", "GMP"],
  ["TPE", "TSA"],
  ["BKK", "DMK"],
  ["CDG", "ORY"],
  ["LHR", "LGW"],
]

/* ── Destinations ─────────────────────────────────────────────────────── */

extension Destinations {
  public static let all: [Destination] = [
  Destination(
    id: .worldwide,
    names: [.en: "Anywhere", .ja: "世界のどこか"],
    countryCodes: [],
    regionCode: nil,
    querySuffix: nil,
    timeZone: "UTC",
    currency: DestinationCurrency(code: "USD", bandGlyph: "•"),
    center: GeoPoint(latitude: 20, longitude: 0),
    overviewZoom: 2,
    bounds: nil,
    // Until the country is known, keep the product's long-standing lean toward
    // transit: recommending a train that turns out to be a bus is a smaller
    // error than quietly budgeting every leg as a taxi.
    mobility: .transit_first,
    meals: DestinationMeals(lunch: MealWindow(start: hour(12), end: hour(14)), dinner: MealWindow(start: hour(18, 30), end: hour(21))),
    hotelFacts: nil,
    airports: [],
    cuisine: [.en: ["a local speciality", "a casual sit-down meal", "a café break"], .ja: ["その土地の名物", "気軽に座れる食事", "カフェ休憩"]],
    notes: [.en: [], .ja: []],
    sample: nil,
  ),
  Destination(
    id: .japan,
    names: [.en: "Japan", .ja: "日本"],
    countryCodes: ["JP"],
    regionCode: "JP",
    querySuffix: "Japan",
    timeZone: "Asia/Tokyo",
    currency: DestinationCurrency(code: "JPY", bandGlyph: "¥"),
    center: GeoPoint(latitude: 36.2048, longitude: 138.2529),
    overviewZoom: 5,
    bounds: GeoBounds(south: 20, west: 122, north: 46, east: 154),
    mobility: .transit_first,
    meals: DestinationMeals(lunch: MealWindow(start: hour(11), end: hour(14, 30)), dinner: MealWindow(start: hour(17, 30), end: hour(21))),
    hotelFacts: .rakuten,
    airports: japanAirports,
    cuisine: [.en: ["local Japanese", "casual set meal", "café break"], .ja: ["その街らしい和食", "気軽な定食", "カフェ休憩"]],
    notes: [.en: [
        "Many museums close on Mondays (or the next weekday when Monday is a holiday).",
        "The most popular timed venues sell out days ahead; some run a lottery rather than a queue.",
      ], .ja: [
        "美術館・博物館は月曜休館が多い（祝日の場合は翌平日）。",
        "人気の日時指定施設は数日前に売り切れることがあり、抽選制のものもある。",
      ]],
    sample: nil,
  ),
  Destination(
    id: .switzerland,
    names: [.en: "Switzerland", .ja: "スイス"],
    countryCodes: ["CH", "LI"],
    regionCode: "CH",
    querySuffix: "Switzerland",
    timeZone: "Europe/Zurich",
    currency: DestinationCurrency(code: "CHF", bandGlyph: "₣"),
    center: GeoPoint(latitude: 46.8182, longitude: 8.2275),
    overviewZoom: 8,
    bounds: GeoBounds(south: 45.6, west: 5.8, north: 47.9, east: 10.6),
    mobility: .transit_first,
    // Kitchens in much of Switzerland stop serving well before closing time,
    // so an itinerary that puts dinner at 21:30 quietly plans a closed door.
    meals: DestinationMeals(lunch: MealWindow(start: hour(11, 45), end: hour(13, 45)), dinner: MealWindow(start: hour(18), end: hour(20, 30))),
    hotelFacts: nil,
    sundayClosing: true,
    airports: swissAirports,
    cuisine: [.en: ["Swiss classics", "a mountain restaurant", "a café or bakery"], .ja: ["スイスの定番料理", "山のレストラン", "カフェ・ベーカリー"]],
    notes: [.en: [
        "Shops and many restaurants close on Sundays; station and airport outlets are the usual exception.",
        "Mountain railways and cable cars run to a fixed timetable with a published last descent, and several close for maintenance in spring and late autumn.",
        "High-altitude viewpoints are weather-dependent — check the summit webcam the morning you go.",
      ], .ja: [
        "日曜は商店と多くのレストランが休業。駅構内と空港はだいたい例外。",
        "登山鉄道・ロープウェイは時刻表制で「最終下り」が決まっている。春と晩秋には整備運休する路線もある。",
        "高所の展望台は天候次第。当日の朝に山頂ライブカメラを確認するのが確実。",
      ]],
    sample: [.en: """
      Lucerne Chapel Bridge
      Mount Rigi
      Interlaken
      Jungfraujoch — must
      Lauterbrunnen
      Zermatt
      Gornergrat
      Bern Old Town
      """, .ja: """
      ルツェルン カペル橋
      リギ山
      インターラーケン
      ユングフラウヨッホ — 必須
      ラウターブルンネン
      ツェルマット
      ゴルナーグラート
      ベルン旧市街
      """],
    // Widely published landmark coordinates; the sample must build offline.
    sampleStops: [
      DestinationSampleStop(names: [.en: "Lucerne Chapel Bridge", .ja: "ルツェルン カペル橋"], area: [.en: "Lucerne", .ja: "ルツェルン"], latitude: 47.0517, longitude: 8.3073, stayMinutes: 45, openingHoursApplicable: false),
      DestinationSampleStop(names: [.en: "Mount Rigi", .ja: "リギ山"], area: [.en: "Arth", .ja: "アルト"], latitude: 47.0567, longitude: 8.4854, stayMinutes: 150, openingHoursApplicable: false),
      DestinationSampleStop(names: [.en: "Interlaken", .ja: "インターラーケン"], area: [.en: "Interlaken", .ja: "インターラーケン"], latitude: 46.6863, longitude: 7.8632, stayMinutes: 90, openingHoursApplicable: false),
      DestinationSampleStop(names: [.en: "Jungfraujoch", .ja: "ユングフラウヨッホ"], area: [.en: "Lauterbrunnen", .ja: "ラウターブルンネン"], latitude: 46.5474, longitude: 7.9793, stayMinutes: 150),
      DestinationSampleStop(names: [.en: "Lauterbrunnen", .ja: "ラウターブルンネン"], area: [.en: "Lauterbrunnen", .ja: "ラウターブルンネン"], latitude: 46.5936, longitude: 7.9081, stayMinutes: 60, openingHoursApplicable: false),
      DestinationSampleStop(names: [.en: "Zermatt", .ja: "ツェルマット"], area: [.en: "Zermatt", .ja: "ツェルマット"], latitude: 46.0207, longitude: 7.7491, stayMinutes: 120, openingHoursApplicable: false),
      DestinationSampleStop(names: [.en: "Gornergrat", .ja: "ゴルナーグラート"], area: [.en: "Zermatt", .ja: "ツェルマット"], latitude: 45.9833, longitude: 7.7842, stayMinutes: 120),
      DestinationSampleStop(names: [.en: "Bern Old Town", .ja: "ベルン旧市街"], area: [.en: "Bern", .ja: "ベルン"], latitude: 46.948, longitude: 7.4474, stayMinutes: 90, openingHoursApplicable: false),
    ],
  ),
  Destination(
    id: .korea,
    names: [.en: "South Korea", .ja: "韓国"],
    countryCodes: ["KR"],
    regionCode: "KR",
    querySuffix: "South Korea",
    timeZone: "Asia/Seoul",
    currency: DestinationCurrency(code: "KRW", bandGlyph: "₩"),
    center: GeoPoint(latitude: 36.5, longitude: 127.85),
    overviewZoom: 7,
    bounds: GeoBounds(south: 33, west: 125, north: 38.7, east: 131.9),
    mobility: .transit_first,
    meals: DestinationMeals(lunch: MealWindow(start: hour(11, 30), end: hour(14)), dinner: MealWindow(start: hour(17, 30), end: hour(21))),
    hotelFacts: nil,
    airports: [
      DestinationAirport(code: "ICN", names: [.en: "Incheon", .ja: "仁川空港"], latitude: 37.4602, longitude: 126.4407, transferMinutes: 70, internationalDepartureMinutes: 180, sourceUrl: "https://www.airport.kr/ap/en/index.do"),
      DestinationAirport(code: "GMP", names: [.en: "Gimpo", .ja: "金浦空港"], latitude: 37.5583, longitude: 126.7906, transferMinutes: 35, internationalDepartureMinutes: 120, sourceUrl: "https://www.airport.co.kr/gimpoeng/index.do"),
      DestinationAirport(code: "PUS", names: [.en: "Busan Gimhae", .ja: "釜山金海空港"], latitude: 35.1795, longitude: 128.9382, transferMinutes: 45, internationalDepartureMinutes: 150, sourceUrl: "https://www.airport.co.kr/gimhaeeng/index.do"),
    ],
    cuisine: [.en: ["Korean staples", "a market meal", "a café break"], .ja: ["韓国の定番", "市場のごはん", "カフェ休憩"]],
    notes: [.en: [], .ja: []],
    sample: nil,
  ),
  Destination(
    id: .taiwan,
    names: [.en: "Taiwan", .ja: "台湾"],
    countryCodes: ["TW"],
    regionCode: "TW",
    querySuffix: "Taiwan",
    timeZone: "Asia/Taipei",
    currency: DestinationCurrency(code: "TWD", bandGlyph: "$"),
    center: GeoPoint(latitude: 23.7, longitude: 120.96),
    overviewZoom: 7,
    bounds: GeoBounds(south: 21.5, west: 118, north: 25.5, east: 122.5),
    mobility: .transit_first,
    meals: DestinationMeals(lunch: MealWindow(start: hour(11, 30), end: hour(14)), dinner: MealWindow(start: hour(17, 30), end: hour(21))),
    hotelFacts: nil,
    airports: [
      DestinationAirport(code: "TPE", names: [.en: "Taoyuan", .ja: "桃園空港"], latitude: 25.0777, longitude: 121.2328, transferMinutes: 55, internationalDepartureMinutes: 150, sourceUrl: "https://www.taoyuan-airport.com/english"),
      DestinationAirport(code: "TSA", names: [.en: "Taipei Songshan", .ja: "台北松山空港"], latitude: 25.0697, longitude: 121.5522, transferMinutes: 20, internationalDepartureMinutes: 120, sourceUrl: "https://www.tsa.gov.tw/en/"),
    ],
    cuisine: [.en: ["night-market food", "a noodle or rice shop", "a tea house"], .ja: ["夜市の食べ歩き", "麺・ごはんの店", "茶藝館"]],
    notes: [.en: [], .ja: []],
    sample: nil,
  ),
  Destination(
    id: .hongkong,
    names: [.en: "Hong Kong", .ja: "香港"],
    countryCodes: ["HK"],
    regionCode: "HK",
    querySuffix: "Hong Kong",
    timeZone: "Asia/Hong_Kong",
    currency: DestinationCurrency(code: "HKD", bandGlyph: "$"),
    center: GeoPoint(latitude: 22.3193, longitude: 114.1694),
    overviewZoom: 10,
    bounds: GeoBounds(south: 22.1, west: 113.8, north: 22.6, east: 114.5),
    mobility: .transit_first,
    meals: DestinationMeals(lunch: MealWindow(start: hour(12), end: hour(14)), dinner: MealWindow(start: hour(18), end: hour(21, 30))),
    hotelFacts: nil,
    airports: [
      DestinationAirport(code: "HKG", names: [.en: "Hong Kong", .ja: "香港国際空港"], latitude: 22.308, longitude: 113.9185, transferMinutes: 35, internationalDepartureMinutes: 150, sourceUrl: "https://www.hongkongairport.com/"),
    ],
    cuisine: [.en: ["dim sum", "a cha chaan teng", "a tea break"], .ja: ["飲茶", "茶餐廳", "お茶休憩"]],
    notes: [.en: [], .ja: []],
    sample: nil,
  ),
  Destination(
    id: .singapore,
    names: [.en: "Singapore", .ja: "シンガポール"],
    countryCodes: ["SG"],
    regionCode: "SG",
    querySuffix: "Singapore",
    timeZone: "Asia/Singapore",
    currency: DestinationCurrency(code: "SGD", bandGlyph: "$"),
    center: GeoPoint(latitude: 1.3521, longitude: 103.8198),
    overviewZoom: 11,
    bounds: GeoBounds(south: 1.1, west: 103.5, north: 1.5, east: 104.2),
    mobility: .transit_first,
    meals: DestinationMeals(lunch: MealWindow(start: hour(12), end: hour(14)), dinner: MealWindow(start: hour(18, 30), end: hour(21, 30))),
    hotelFacts: nil,
    airports: [
      DestinationAirport(code: "SIN", names: [.en: "Changi", .ja: "チャンギ空港"], latitude: 1.3644, longitude: 103.9915, transferMinutes: 35, internationalDepartureMinutes: 180, sourceUrl: "https://www.changiairport.com/"),
    ],
    cuisine: [.en: ["a hawker centre", "a local one-dish meal", "a kopitiam break"], .ja: ["ホーカーセンター", "名物の一皿", "コピティアム休憩"]],
    notes: [.en: [], .ja: []],
    sample: nil,
  ),
  Destination(
    id: .thailand,
    names: [.en: "Thailand", .ja: "タイ"],
    countryCodes: ["TH"],
    regionCode: "TH",
    querySuffix: "Thailand",
    timeZone: "Asia/Bangkok",
    currency: DestinationCurrency(code: "THB", bandGlyph: "฿"),
    center: GeoPoint(latitude: 15.87, longitude: 100.99),
    overviewZoom: 6,
    bounds: GeoBounds(south: 5.5, west: 97, north: 20.6, east: 106),
    mobility: .balanced,
    meals: DestinationMeals(lunch: MealWindow(start: hour(11, 30), end: hour(14)), dinner: MealWindow(start: hour(18), end: hour(21, 30))),
    hotelFacts: nil,
    airports: [
      DestinationAirport(code: "BKK", names: [.en: "Suvarnabhumi", .ja: "スワンナプーム空港"], latitude: 13.69, longitude: 100.7501, transferMinutes: 60, internationalDepartureMinutes: 180, sourceUrl: "https://www.suvarnabhumiairport.com/en"),
      DestinationAirport(code: "DMK", names: [.en: "Don Mueang", .ja: "ドンムアン空港"], latitude: 13.9126, longitude: 100.6068, transferMinutes: 55, internationalDepartureMinutes: 150, sourceUrl: "https://www.donmueangairport.com/en"),
      DestinationAirport(code: "HKT", names: [.en: "Phuket", .ja: "プーケット空港"], latitude: 8.1132, longitude: 98.3169, transferMinutes: 60, internationalDepartureMinutes: 150, sourceUrl: "https://www.phuketairportthai.com/en"),
    ],
    cuisine: [.en: ["Thai street food", "a rice or noodle shop", "an iced-coffee stop"], .ja: ["タイの屋台料理", "ごはん・麺の食堂", "アイスコーヒー休憩"]],
    notes: [.en: ["Temples enforce a dress code — covered shoulders and knees."], .ja: ["寺院は服装規定あり（肩と膝が隠れる服装）。"]],
    sample: nil,
  ),
  Destination(
    id: .vietnam,
    names: [.en: "Vietnam", .ja: "ベトナム"],
    countryCodes: ["VN"],
    regionCode: "VN",
    querySuffix: "Vietnam",
    timeZone: "Asia/Ho_Chi_Minh",
    currency: DestinationCurrency(code: "VND", bandGlyph: "₫"),
    center: GeoPoint(latitude: 14.06, longitude: 108.28),
    overviewZoom: 6,
    bounds: GeoBounds(south: 8, west: 102, north: 23.5, east: 110),
    mobility: .balanced,
    meals: DestinationMeals(lunch: MealWindow(start: hour(11, 30), end: hour(13, 30)), dinner: MealWindow(start: hour(18), end: hour(21))),
    hotelFacts: nil,
    airports: [
      DestinationAirport(code: "SGN", names: [.en: "Ho Chi Minh City", .ja: "タンソンニャット空港"], latitude: 10.8188, longitude: 106.652, transferMinutes: 40, internationalDepartureMinutes: 180, sourceUrl: "https://www.vietnamairport.vn/tansonnhatairport/en"),
      DestinationAirport(code: "HAN", names: [.en: "Hanoi Noi Bai", .ja: "ノイバイ空港"], latitude: 21.2212, longitude: 105.8072, transferMinutes: 50, internationalDepartureMinutes: 180, sourceUrl: "https://www.vietnamairport.vn/noibaiairport/en"),
      DestinationAirport(code: "DAD", names: [.en: "Da Nang", .ja: "ダナン空港"], latitude: 16.0439, longitude: 108.1994, transferMinutes: 20, internationalDepartureMinutes: 150, sourceUrl: "https://www.vietnamairport.vn/danangairport/en"),
    ],
    cuisine: [.en: ["a pho or banh mi stop", "a local rice shop", "a Vietnamese coffee break"], .ja: ["フォー・バインミー", "地元の食堂", "ベトナムコーヒー休憩"]],
    notes: [.en: [], .ja: []],
    sample: nil,
  ),
  Destination(
    id: .indonesia,
    names: [.en: "Indonesia", .ja: "インドネシア"],
    countryCodes: ["ID"],
    regionCode: "ID",
    querySuffix: "Indonesia",
    timeZone: "Asia/Jakarta",
    currency: DestinationCurrency(code: "IDR", bandGlyph: "•"),
    center: GeoPoint(latitude: -2.55, longitude: 118.02),
    overviewZoom: 5,
    bounds: GeoBounds(south: -11.5, west: 94, north: 6.5, east: 141.5),
    mobility: .car_first,
    meals: DestinationMeals(lunch: MealWindow(start: hour(12), end: hour(14)), dinner: MealWindow(start: hour(18), end: hour(21))),
    hotelFacts: nil,
    airports: [
      DestinationAirport(code: "CGK", names: [.en: "Jakarta Soekarno-Hatta", .ja: "スカルノハッタ空港"], latitude: -6.1256, longitude: 106.6558, transferMinutes: 70, internationalDepartureMinutes: 180, sourceUrl: "https://soekarnohatta-airport.co.id/en"),
      DestinationAirport(code: "DPS", names: [.en: "Bali Denpasar", .ja: "デンパサール空港"], latitude: -8.7482, longitude: 115.1675, transferMinutes: 40, internationalDepartureMinutes: 180, sourceUrl: "https://bali-airport.com/en"),
    ],
    cuisine: [.en: ["a warung meal", "grilled seafood", "a coffee stop"], .ja: ["ワルンの食事", "焼き魚・シーフード", "コーヒー休憩"]],
    notes: [.en: [], .ja: []],
    sample: nil,
  ),
  Destination(
    id: .uae,
    names: [.en: "United Arab Emirates", .ja: "アラブ首長国連邦"],
    countryCodes: ["AE"],
    regionCode: "AE",
    querySuffix: "United Arab Emirates",
    timeZone: "Asia/Dubai",
    currency: DestinationCurrency(code: "AED", bandGlyph: "•"),
    center: GeoPoint(latitude: 24.4, longitude: 54.4),
    overviewZoom: 7,
    bounds: GeoBounds(south: 22, west: 51, north: 26.5, east: 56.5),
    mobility: .car_first,
    meals: DestinationMeals(lunch: MealWindow(start: hour(12, 30), end: hour(15)), dinner: MealWindow(start: hour(19), end: hour(22, 30))),
    hotelFacts: nil,
    airports: [
      DestinationAirport(code: "DXB", names: [.en: "Dubai", .ja: "ドバイ空港"], latitude: 25.2532, longitude: 55.3657, transferMinutes: 30, internationalDepartureMinutes: 180, sourceUrl: "https://www.dubaiairports.ae/"),
      DestinationAirport(code: "AUH", names: [.en: "Abu Dhabi", .ja: "アブダビ空港"], latitude: 24.433, longitude: 54.6511, transferMinutes: 45, internationalDepartureMinutes: 180, sourceUrl: "https://www.zayedinternationalairport.ae/en"),
    ],
    cuisine: [.en: ["Emirati and Levantine food", "a mall food hall", "a café break"], .ja: ["中東料理", "モールのフードホール", "カフェ休憩"]],
    notes: [.en: ["Outdoor sightseeing is limited by heat from roughly June to September."], .ja: ["6〜9月ごろは暑さで屋外の観光が制限される。"]],
    sample: nil,
  ),
  Destination(
    id: .france,
    names: [.en: "France", .ja: "フランス"],
    countryCodes: ["FR", "MC"],
    regionCode: "FR",
    querySuffix: "France",
    timeZone: "Europe/Paris",
    currency: DestinationCurrency(code: "EUR", bandGlyph: "€"),
    center: GeoPoint(latitude: 46.6, longitude: 2.35),
    overviewZoom: 6,
    bounds: GeoBounds(south: 41, west: -5.5, north: 51.5, east: 10),
    mobility: .transit_first,
    meals: DestinationMeals(lunch: MealWindow(start: hour(12), end: hour(14)), dinner: MealWindow(start: hour(19, 30), end: hour(22))),
    hotelFacts: nil,
    airports: [
      DestinationAirport(code: "CDG", names: [.en: "Paris Charles de Gaulle", .ja: "シャルル・ド・ゴール空港"], latitude: 49.0097, longitude: 2.5479, transferMinutes: 50, internationalDepartureMinutes: 180, sourceUrl: "https://www.parisaeroport.fr/en"),
      DestinationAirport(code: "ORY", names: [.en: "Paris Orly", .ja: "オルリー空港"], latitude: 48.7233, longitude: 2.3794, transferMinutes: 40, internationalDepartureMinutes: 150, sourceUrl: "https://www.parisaeroport.fr/en"),
      DestinationAirport(code: "NCE", names: [.en: "Nice", .ja: "ニース空港"], latitude: 43.6584, longitude: 7.2159, transferMinutes: 25, internationalDepartureMinutes: 150, sourceUrl: "https://www.nice.aeroport.fr/en"),
    ],
    cuisine: [.en: ["a bistro lunch", "a boulangerie stop", "a café terrace"], .ja: ["ビストロのランチ", "ブーランジェリー", "カフェのテラス"]],
    notes: [.en: [
        "Most national museums close one weekday — commonly Monday or Tuesday.",
        "Restaurant kitchens usually close between lunch and dinner service.",
      ], .ja: [
        "国立美術館の多くは週に1日休館（月曜か火曜が多い）。",
        "レストランはランチとディナーの間に厨房を閉める店が多い。",
      ]],
    sample: nil,
  ),
  Destination(
    id: .italy,
    names: [.en: "Italy", .ja: "イタリア"],
    countryCodes: ["IT", "VA", "SM"],
    regionCode: "IT",
    querySuffix: "Italy",
    timeZone: "Europe/Rome",
    currency: DestinationCurrency(code: "EUR", bandGlyph: "€"),
    center: GeoPoint(latitude: 42.5, longitude: 12.5),
    overviewZoom: 6,
    bounds: GeoBounds(south: 35.4, west: 6.5, north: 47.2, east: 18.6),
    mobility: .transit_first,
    meals: DestinationMeals(lunch: MealWindow(start: hour(12, 30), end: hour(14, 30)), dinner: MealWindow(start: hour(19, 30), end: hour(22))),
    hotelFacts: nil,
    airports: [
      DestinationAirport(code: "FCO", names: [.en: "Rome Fiumicino", .ja: "ローマ フィウミチーノ空港"], latitude: 41.8003, longitude: 12.2389, transferMinutes: 45, internationalDepartureMinutes: 180, sourceUrl: "https://www.adr.it/web/aeroporti-di-roma-en"),
      DestinationAirport(code: "MXP", names: [.en: "Milan Malpensa", .ja: "ミラノ マルペンサ空港"], latitude: 45.6306, longitude: 8.7281, transferMinutes: 55, internationalDepartureMinutes: 180, sourceUrl: "https://www.milanomalpensa-airport.com/en"),
      DestinationAirport(code: "VCE", names: [.en: "Venice Marco Polo", .ja: "ヴェネツィア空港"], latitude: 45.5053, longitude: 12.3519, transferMinutes: 45, internationalDepartureMinutes: 150, sourceUrl: "https://www.veniceairport.it/en/"),
    ],
    cuisine: [.en: ["a trattoria meal", "a pizzeria", "an espresso bar"], .ja: ["トラットリア", "ピッツェリア", "エスプレッソバール"]],
    notes: [.en: [
        "Major sites (Uffizi, Last Supper, Colosseum) run on timed entry booked ahead.",
        "Many churches close in the early afternoon.",
      ], .ja: [
        "主要施設（ウフィツィ、最後の晩餐、コロッセオなど）は事前予約の時間指定入場。",
        "教会は昼過ぎに閉まるところが多い。",
      ]],
    sample: nil,
  ),
  Destination(
    id: .spain,
    names: [.en: "Spain", .ja: "スペイン"],
    countryCodes: ["ES", "AD"],
    regionCode: "ES",
    querySuffix: "Spain",
    timeZone: "Europe/Madrid",
    currency: DestinationCurrency(code: "EUR", bandGlyph: "€"),
    center: GeoPoint(latitude: 40, longitude: -3.7),
    overviewZoom: 6,
    bounds: GeoBounds(south: 27, west: -18.5, north: 44, east: 4.5),
    mobility: .transit_first,
    // Spain really does eat this late; planning dinner at 18:30 books an empty room.
    meals: DestinationMeals(lunch: MealWindow(start: hour(14), end: hour(16)), dinner: MealWindow(start: hour(21), end: hour(23))),
    hotelFacts: nil,
    airports: [
      DestinationAirport(code: "MAD", names: [.en: "Madrid Barajas", .ja: "マドリード バラハス空港"], latitude: 40.4719, longitude: -3.5626, transferMinutes: 40, internationalDepartureMinutes: 180, sourceUrl: "https://www.aena.es/en/adolfo-suarez-madrid-barajas.html"),
      DestinationAirport(code: "BCN", names: [.en: "Barcelona El Prat", .ja: "バルセロナ空港"], latitude: 41.2974, longitude: 2.0833, transferMinutes: 35, internationalDepartureMinutes: 180, sourceUrl: "https://www.aena.es/en/josep-tarradellas-barcelona-el-prat.html"),
    ],
    cuisine: [.en: ["tapas", "a menú del día lunch", "a café con leche stop"], .ja: ["タパス", "メニュー・デル・ディア（日替わり定食）", "カフェ休憩"]],
    notes: [.en: [
        "Lunch runs roughly 14:00–16:00 and dinner rarely starts before 21:00.",
        "Smaller shops close in the afternoon and reopen in the early evening.",
      ], .ja: [
        "昼食は14〜16時、夕食は21時以降が普通。",
        "小さな店は午後に閉め、夕方に再開する。",
      ]],
    sample: nil,
  ),
  Destination(
    id: .portugal,
    names: [.en: "Portugal", .ja: "ポルトガル"],
    countryCodes: ["PT"],
    regionCode: "PT",
    querySuffix: "Portugal",
    timeZone: "Europe/Lisbon",
    currency: DestinationCurrency(code: "EUR", bandGlyph: "€"),
    center: GeoPoint(latitude: 39.5, longitude: -8),
    overviewZoom: 7,
    bounds: GeoBounds(south: 30, west: -32, north: 42.5, east: -6),
    mobility: .balanced,
    meals: DestinationMeals(lunch: MealWindow(start: hour(12, 30), end: hour(15)), dinner: MealWindow(start: hour(19, 30), end: hour(22))),
    hotelFacts: nil,
    airports: [
      DestinationAirport(code: "LIS", names: [.en: "Lisbon", .ja: "リスボン空港"], latitude: 38.7742, longitude: -9.1342, transferMinutes: 25, internationalDepartureMinutes: 180, sourceUrl: "https://www.ana.pt/en/lis/home"),
      DestinationAirport(code: "OPO", names: [.en: "Porto", .ja: "ポルト空港"], latitude: 41.2481, longitude: -8.6814, transferMinutes: 35, internationalDepartureMinutes: 150, sourceUrl: "https://www.ana.pt/en/opo/home"),
    ],
    cuisine: [.en: ["a tasca meal", "grilled fish", "a pastelaria stop"], .ja: ["タスカ（大衆食堂）", "魚のグリル", "パステラリア（菓子店）"]],
    notes: [.en: [], .ja: []],
    sample: nil,
  ),
  Destination(
    id: .uk,
    names: [.en: "United Kingdom", .ja: "イギリス"],
    countryCodes: ["GB"],
    regionCode: "GB",
    querySuffix: "United Kingdom",
    timeZone: "Europe/London",
    currency: DestinationCurrency(code: "GBP", bandGlyph: "£"),
    center: GeoPoint(latitude: 54, longitude: -2.5),
    overviewZoom: 6,
    bounds: GeoBounds(south: 49, west: -11, north: 61, east: 2.2),
    mobility: .transit_first,
    meals: DestinationMeals(lunch: MealWindow(start: hour(12), end: hour(14)), dinner: MealWindow(start: hour(18), end: hour(21))),
    hotelFacts: nil,
    airports: [
      DestinationAirport(code: "LHR", names: [.en: "London Heathrow", .ja: "ヒースロー空港"], latitude: 51.47, longitude: -0.4543, transferMinutes: 55, internationalDepartureMinutes: 180, sourceUrl: "https://www.heathrow.com/"),
      DestinationAirport(code: "LGW", names: [.en: "London Gatwick", .ja: "ガトウィック空港"], latitude: 51.1537, longitude: -0.1821, transferMinutes: 50, internationalDepartureMinutes: 180, sourceUrl: "https://www.gatwickairport.com/"),
      DestinationAirport(code: "MAN", names: [.en: "Manchester", .ja: "マンチェスター空港"], latitude: 53.3537, longitude: -2.275, transferMinutes: 25, internationalDepartureMinutes: 180, sourceUrl: "https://www.manchesterairport.co.uk/"),
    ],
    cuisine: [.en: ["a pub meal", "a market food hall", "afternoon tea or a café"], .ja: ["パブの食事", "マーケットのフードホール", "アフタヌーンティー・カフェ"]],
    notes: [.en: ["Sunday opening hours are shorter, and pub kitchens often stop serving before the bar closes."], .ja: ["日曜は営業時間が短い。パブは閉店前に厨房が終わることが多い。"]],
    sample: nil,
  ),
  Destination(
    id: .germany,
    names: [.en: "Germany", .ja: "ドイツ"],
    countryCodes: ["DE"],
    regionCode: "DE",
    querySuffix: "Germany",
    timeZone: "Europe/Berlin",
    currency: DestinationCurrency(code: "EUR", bandGlyph: "€"),
    center: GeoPoint(latitude: 51.16, longitude: 10.45),
    overviewZoom: 6,
    bounds: GeoBounds(south: 47, west: 5.5, north: 55.2, east: 15.2),
    mobility: .transit_first,
    meals: DestinationMeals(lunch: MealWindow(start: hour(12), end: hour(14)), dinner: MealWindow(start: hour(18), end: hour(21))),
    hotelFacts: nil,
    sundayClosing: true,
    airports: [
      DestinationAirport(code: "FRA", names: [.en: "Frankfurt", .ja: "フランクフルト空港"], latitude: 50.0379, longitude: 8.5622, transferMinutes: 20, internationalDepartureMinutes: 180, sourceUrl: "https://www.frankfurt-airport.com/en.html"),
      DestinationAirport(code: "MUC", names: [.en: "Munich", .ja: "ミュンヘン空港"], latitude: 48.3538, longitude: 11.7861, transferMinutes: 45, internationalDepartureMinutes: 180, sourceUrl: "https://www.munich-airport.com/"),
      DestinationAirport(code: "BER", names: [.en: "Berlin Brandenburg", .ja: "ベルリン空港"], latitude: 52.3667, longitude: 13.5033, transferMinutes: 40, internationalDepartureMinutes: 180, sourceUrl: "https://ber.berlin-airport.de/en.html"),
    ],
    cuisine: [.en: ["a Gasthaus meal", "a bakery or imbiss", "a Kaffee und Kuchen break"], .ja: ["ガストハウスの食事", "パン屋・軽食スタンド", "コーヒーとケーキ"]],
    notes: [.en: ["Shops close on Sundays; station supermarkets are the usual exception."], .ja: ["日曜は商店が休業。駅のスーパーはだいたい例外。"]],
    sample: nil,
  ),
  Destination(
    id: .austria,
    names: [.en: "Austria", .ja: "オーストリア"],
    countryCodes: ["AT"],
    regionCode: "AT",
    querySuffix: "Austria",
    timeZone: "Europe/Vienna",
    currency: DestinationCurrency(code: "EUR", bandGlyph: "€"),
    center: GeoPoint(latitude: 47.52, longitude: 14.55),
    overviewZoom: 7,
    bounds: GeoBounds(south: 46.3, west: 9.4, north: 49.1, east: 17.2),
    mobility: .transit_first,
    meals: DestinationMeals(lunch: MealWindow(start: hour(12), end: hour(14)), dinner: MealWindow(start: hour(18), end: hour(21))),
    hotelFacts: nil,
    sundayClosing: true,
    airports: [
      DestinationAirport(code: "VIE", names: [.en: "Vienna", .ja: "ウィーン空港"], latitude: 48.1103, longitude: 16.5697, transferMinutes: 25, internationalDepartureMinutes: 180, sourceUrl: "https://www.viennaairport.com/en/passengers"),
      DestinationAirport(code: "SZG", names: [.en: "Salzburg", .ja: "ザルツブルク空港"], latitude: 47.7933, longitude: 13.0043, transferMinutes: 20, internationalDepartureMinutes: 120, sourceUrl: "https://www.salzburg-airport.com/en/"),
      DestinationAirport(code: "INN", names: [.en: "Innsbruck", .ja: "インスブルック空港"], latitude: 47.2602, longitude: 11.344, transferMinutes: 20, internationalDepartureMinutes: 120, sourceUrl: "https://www.innsbruck-airport.com/en"),
    ],
    cuisine: [.en: ["a Gasthaus meal", "a Viennese coffee house", "a bakery stop"], .ja: ["ガストハウスの食事", "ウィーンのカフェハウス", "パン屋"]],
    notes: [.en: ["Shops close on Sundays; mountain lifts follow a summer/winter season calendar."], .ja: ["日曜は商店が休業。山岳リフトは夏・冬のシーズン制で運休期間がある。"]],
    sample: nil,
  ),
  Destination(
    id: .netherlands,
    names: [.en: "Netherlands", .ja: "オランダ"],
    countryCodes: ["NL", "BE", "LU"],
    regionCode: "NL",
    querySuffix: "Netherlands",
    timeZone: "Europe/Amsterdam",
    currency: DestinationCurrency(code: "EUR", bandGlyph: "€"),
    center: GeoPoint(latitude: 52.13, longitude: 5.29),
    overviewZoom: 8,
    bounds: GeoBounds(south: 49.4, west: 2.5, north: 53.7, east: 7.3),
    mobility: .transit_first,
    meals: DestinationMeals(lunch: MealWindow(start: hour(12), end: hour(14)), dinner: MealWindow(start: hour(18), end: hour(21))),
    hotelFacts: nil,
    airports: [
      DestinationAirport(code: "AMS", names: [.en: "Amsterdam Schiphol", .ja: "スキポール空港"], latitude: 52.3105, longitude: 4.7683, transferMinutes: 25, internationalDepartureMinutes: 180, sourceUrl: "https://www.schiphol.nl/en/"),
    ],
    cuisine: [.en: ["a brown café meal", "a market stall", "a coffee and appeltaart stop"], .ja: ["ブラウンカフェの食事", "市場の屋台", "コーヒーとアップルパイ"]],
    notes: [.en: [], .ja: []],
    sample: nil,
  ),
  Destination(
    id: .iceland,
    names: [.en: "Iceland", .ja: "アイスランド"],
    countryCodes: ["IS"],
    regionCode: "IS",
    querySuffix: "Iceland",
    timeZone: "Atlantic/Reykjavik",
    currency: DestinationCurrency(code: "ISK", bandGlyph: "•"),
    center: GeoPoint(latitude: 64.96, longitude: -19.02),
    overviewZoom: 6,
    bounds: GeoBounds(south: 63, west: -25, north: 67, east: -13),
    mobility: .car_first,
    meals: DestinationMeals(lunch: MealWindow(start: hour(12), end: hour(14)), dinner: MealWindow(start: hour(18), end: hour(21))),
    hotelFacts: nil,
    airports: [
      DestinationAirport(code: "KEF", names: [.en: "Keflavík", .ja: "ケプラヴィーク空港"], latitude: 63.985, longitude: -22.6056, transferMinutes: 50, internationalDepartureMinutes: 150, sourceUrl: "https://www.isavia.is/en/keflavik-airport"),
    ],
    cuisine: [.en: ["a soup or seafood stop", "a bakery", "a coffee break"], .ja: ["スープ・シーフードの店", "ベーカリー", "コーヒー休憩"]],
    notes: [.en: [
        "Daylight is very short in winter and roads close at short notice — check road.is before a driving day.",
        "Distances between stops are long; a day usually holds fewer places than it looks.",
      ], .ja: [
        "冬は日照が非常に短く、道路も急に閉鎖される。運転する日は road.is を確認。",
        "拠点間の距離が長く、1日に入る場所は見た目より少ない。",
      ]],
    sample: nil,
  ),
  Destination(
    id: .norway,
    names: [.en: "Norway", .ja: "ノルウェー"],
    countryCodes: ["NO"],
    regionCode: "NO",
    querySuffix: "Norway",
    timeZone: "Europe/Oslo",
    currency: DestinationCurrency(code: "NOK", bandGlyph: "•"),
    center: GeoPoint(latitude: 62, longitude: 10),
    overviewZoom: 5,
    bounds: GeoBounds(south: 57.5, west: 4, north: 71.5, east: 31.5),
    mobility: .balanced,
    meals: DestinationMeals(lunch: MealWindow(start: hour(12), end: hour(14)), dinner: MealWindow(start: hour(17), end: hour(20, 30))),
    hotelFacts: nil,
    airports: [
      DestinationAirport(code: "OSL", names: [.en: "Oslo Gardermoen", .ja: "オスロ空港"], latitude: 60.1939, longitude: 11.1004, transferMinutes: 30, internationalDepartureMinutes: 150, sourceUrl: "https://avinor.no/en/airport/oslo-airport/"),
      DestinationAirport(code: "BGO", names: [.en: "Bergen", .ja: "ベルゲン空港"], latitude: 60.2934, longitude: 5.2181, transferMinutes: 30, internationalDepartureMinutes: 150, sourceUrl: "https://avinor.no/en/airport/bergen-airport/"),
    ],
    cuisine: [.en: ["seafood", "a casual bistro", "a bakery and coffee stop"], .ja: ["シーフード", "気軽なビストロ", "ベーカリーとコーヒー"]],
    notes: [.en: ["Ferries and scenic rail run to a seasonal timetable that thins out sharply in winter."], .ja: ["フェリーや観光列車は季節ダイヤ。冬は大幅に減便される。"]],
    sample: nil,
  ),
  Destination(
    id: .usa,
    names: [.en: "United States", .ja: "アメリカ"],
    countryCodes: ["US"],
    regionCode: "US",
    querySuffix: "USA",
    // The country spans six zones; this one only seeds the default trip date,
    // which the traveller can change. Opening hours are always read in the
    // place's own local calendar day.
    timeZone: "America/New_York",
    currency: DestinationCurrency(code: "USD", bandGlyph: "$"),
    center: GeoPoint(latitude: 39.83, longitude: -98.58),
    overviewZoom: 4,
    bounds: GeoBounds(south: 18, west: -172, north: 72, east: -66),
    mobility: .car_first,
    meals: DestinationMeals(lunch: MealWindow(start: hour(11, 30), end: hour(14)), dinner: MealWindow(start: hour(17, 30), end: hour(21))),
    hotelFacts: nil,
    airports: [
      DestinationAirport(code: "JFK", names: [.en: "New York JFK", .ja: "ニューヨーク JFK空港"], latitude: 40.6413, longitude: -73.7781, transferMinutes: 60, internationalDepartureMinutes: 180, sourceUrl: "https://www.jfkairport.com/"),
      DestinationAirport(code: "LAX", names: [.en: "Los Angeles", .ja: "ロサンゼルス空港"], latitude: 33.9416, longitude: -118.4085, transferMinutes: 50, internationalDepartureMinutes: 180, sourceUrl: "https://www.flylax.com/"),
      DestinationAirport(code: "SFO", names: [.en: "San Francisco", .ja: "サンフランシスコ空港"], latitude: 37.6213, longitude: -122.379, transferMinutes: 40, internationalDepartureMinutes: 180, sourceUrl: "https://www.flysfo.com/"),
    ],
    cuisine: [.en: ["a neighbourhood restaurant", "a diner or deli", "a coffee stop"], .ja: ["近所のレストラン", "ダイナー・デリ", "コーヒー休憩"]],
    notes: [.en: ["Outside the largest cities, transit between stops is thin — a rental car is usually the realistic plan."], .ja: ["大都市以外は公共交通が薄く、レンタカー前提の方が現実的なことが多い。"]],
    sample: nil,
  ),
  Destination(
    id: .canada,
    names: [.en: "Canada", .ja: "カナダ"],
    countryCodes: ["CA"],
    regionCode: "CA",
    querySuffix: "Canada",
    timeZone: "America/Toronto",
    currency: DestinationCurrency(code: "CAD", bandGlyph: "$"),
    center: GeoPoint(latitude: 56.13, longitude: -106.35),
    overviewZoom: 3,
    bounds: GeoBounds(south: 41, west: -142, north: 84, east: -52),
    mobility: .car_first,
    meals: DestinationMeals(lunch: MealWindow(start: hour(11, 30), end: hour(14)), dinner: MealWindow(start: hour(17, 30), end: hour(21))),
    hotelFacts: nil,
    airports: [
      DestinationAirport(code: "YYZ", names: [.en: "Toronto Pearson", .ja: "トロント空港"], latitude: 43.6777, longitude: -79.6248, transferMinutes: 40, internationalDepartureMinutes: 180, sourceUrl: "https://www.torontopearson.com/"),
      DestinationAirport(code: "YVR", names: [.en: "Vancouver", .ja: "バンクーバー空港"], latitude: 49.1967, longitude: -123.1815, transferMinutes: 30, internationalDepartureMinutes: 180, sourceUrl: "https://www.yvr.ca/en"),
    ],
    cuisine: [.en: ["a neighbourhood restaurant", "a brunch spot", "a coffee stop"], .ja: ["近所のレストラン", "ブランチの店", "コーヒー休憩"]],
    notes: [.en: [], .ja: []],
    sample: nil,
  ),
  Destination(
    id: .australia,
    names: [.en: "Australia", .ja: "オーストラリア"],
    countryCodes: ["AU"],
    regionCode: "AU",
    querySuffix: "Australia",
    timeZone: "Australia/Sydney",
    currency: DestinationCurrency(code: "AUD", bandGlyph: "$"),
    center: GeoPoint(latitude: -25.27, longitude: 133.78),
    overviewZoom: 4,
    bounds: GeoBounds(south: -45, west: 110, north: -9, east: 155),
    mobility: .car_first,
    meals: DestinationMeals(lunch: MealWindow(start: hour(12), end: hour(14)), dinner: MealWindow(start: hour(18), end: hour(21))),
    hotelFacts: nil,
    airports: [
      DestinationAirport(code: "SYD", names: [.en: "Sydney", .ja: "シドニー空港"], latitude: -33.9399, longitude: 151.1753, transferMinutes: 30, internationalDepartureMinutes: 180, sourceUrl: "https://www.sydneyairport.com.au/"),
      DestinationAirport(code: "MEL", names: [.en: "Melbourne", .ja: "メルボルン空港"], latitude: -37.669, longitude: 144.841, transferMinutes: 35, internationalDepartureMinutes: 180, sourceUrl: "https://www.melbourneairport.com.au/"),
    ],
    cuisine: [.en: ["a modern Australian meal", "a brunch café", "a bakery stop"], .ja: ["モダン・オーストラリア料理", "ブランチのカフェ", "ベーカリー"]],
    notes: [.en: [], .ja: []],
    sample: nil,
  ),
  Destination(
    id: .newzealand,
    names: [.en: "New Zealand", .ja: "ニュージーランド"],
    countryCodes: ["NZ"],
    regionCode: "NZ",
    querySuffix: "New Zealand",
    timeZone: "Pacific/Auckland",
    currency: DestinationCurrency(code: "NZD", bandGlyph: "$"),
    center: GeoPoint(latitude: -41, longitude: 173),
    overviewZoom: 5,
    bounds: GeoBounds(south: -48, west: 165, north: -33, east: 179.5),
    mobility: .car_first,
    meals: DestinationMeals(lunch: MealWindow(start: hour(12), end: hour(14)), dinner: MealWindow(start: hour(17, 30), end: hour(20, 30))),
    hotelFacts: nil,
    airports: [
      DestinationAirport(code: "AKL", names: [.en: "Auckland", .ja: "オークランド空港"], latitude: -37.0082, longitude: 174.785, transferMinutes: 45, internationalDepartureMinutes: 180, sourceUrl: "https://www.aucklandairport.co.nz/"),
      DestinationAirport(code: "CHC", names: [.en: "Christchurch", .ja: "クライストチャーチ空港"], latitude: -43.4894, longitude: 172.532, transferMinutes: 25, internationalDepartureMinutes: 150, sourceUrl: "https://www.christchurchairport.co.nz/"),
      DestinationAirport(code: "ZQN", names: [.en: "Queenstown", .ja: "クイーンズタウン空港"], latitude: -45.0211, longitude: 168.7392, transferMinutes: 15, internationalDepartureMinutes: 120, sourceUrl: "https://www.queenstownairport.co.nz/"),
    ],
    cuisine: [.en: ["a local restaurant", "a brunch café", "a bakery stop"], .ja: ["地元のレストラン", "ブランチのカフェ", "ベーカリー"]],
    notes: [.en: ["Driving times between regions are long, and rural kitchens often close by 20:30."], .ja: ["地方間の運転時間が長い。地方の飲食店は20時半ごろに厨房が閉まることが多い。"]],
    sample: nil,
  ),
  ]

  public static let worldwide: Destination = all.first { $0.id == .worldwide }!
}
