import Link from "next/link";

export default function PrivacyPage() {
  return (
    <main className="legal-page">
      <header><p>TRIPCHECK / LEGAL / 001</p><h1>Privacy.</h1><span>Last updated August 9, 2026</span></header>
      <section>
        <h2>The short version</h2>
        <p>Your itinerary is parsed and scheduled in your browser. Place and hotel text is sent through protected TripCheck endpoints only when a map provider must locate it. TripCheck does not store the itinerary in a server database or make it available for human review. Up to ten recent plans may be kept only in this browser so you can reopen them.</p>
      </section>
      <section>
        <h2>Weather outlook</h2>
        <p>For trip days inside the forecast horizon, TripCheck may send the calendar date and the approximate geographic centre coordinates of that day to Open-Meteo after the route is already usable. It does not send place names, itinerary text, hotel text or reservation notes. The forecast is shown as optional planning context and never moves a stop or decides whether a plan is feasible.</p>
        <p>Open-Meteo weather data is attributed under CC BY 4.0. Its free service may process request IP addresses and coordinate-bearing web-server logs for service protection and troubleshooting; Open-Meteo states that those logs are deleted after up to 90 days. See the <a href="https://open-meteo.com/en/terms" rel="noreferrer" target="_blank">Open-Meteo terms and privacy information</a>.</p>
      </section>
      <section>
        <h2>Public holidays</h2>
        <p>To warn about public-holiday closures, TripCheck sends only the destination&apos;s two-letter country code and the bare calendar dates of the trip to the <a href="https://date.nager.at" rel="noreferrer" target="_blank">Nager.Date</a> public-holiday service through a protected TripCheck endpoint. No place names, itinerary text or coordinates are included in the request, and it is optional context that never gates the plan.</p>
      </section>
      <section>
        <h2>Planning-time routes</h2>
        <p>After the core dated plan appears, TripCheck automatically sends only the origin and destination coordinates, route mode and planned departure time for each bounded route leg to a protected TripCheck endpoint. That endpoint requests transit, walking or driving duration from Google Maps Platform and progressively replaces estimates. Walking requests do not send the departure time onward to Google. Your pasted notes, hotel text and reservation descriptions are not included.</p>
        <p>The same protected TripCheck endpoint requests Google&apos;s encoded route geometry so the map can follow actual roads and transit paths. The browser receives only the bounded route result; route responses are used in memory for the current page and are not stored by TripCheck. Google processes the provider request under the <a href="https://policies.google.com/privacy" rel="noreferrer" target="_blank">Google Privacy Policy</a>.</p>
      </section>
      <section>
        <h2>Planning-time place checks and recommendations</h2>
        <p>When you create a plan, unknown place names and the hotel or area text you entered are sent to protected TripCheck endpoints so Google Maps Platform can resolve them. The core planner then requests the identity and opening-hour fields needed to check the selected itinerary. A specific hotel name is sent only when it must be resolved or matched as a named property.</p>
        <p>After the resolved places produce a usable core plan, TripCheck automatically looks up bounded hotel and meal shortlists. Automatic hotel discovery sends a search-anchor coordinate, up to ten day-route coordinates, a bounded area label, interface language and destination country to a protected TripCheck endpoint. Meal discovery sends the meal-slot coordinate, a bounded area and query, lunch or dinner, interface language and destination country. For a dated meal slot, its date and planned meal time are sent to the TripCheck endpoint only so returned structured opening periods can be checked in memory; Google receives the bounded location, category or query and language/region fields, not that travel date or time.</p>
        <p>When a completed day has a gap of 30 minutes or more, TripCheck automatically looks up one bounded along-route shortlist. The gap&apos;s length selects only which bounded nearby-place categories are requested. It sends up to twelve sampled coordinates from available Google route geometry (falling back to the ordered stops), interface language and destination country to a protected TripCheck endpoint. If selected lodging is the day&apos;s base, its coordinate may be one of those route points. Existing public place IDs and names are used by the endpoint only to remove duplicate suggestions and are not included in the Google search request. Google receives the coordinates and a bounded nearby-place query. The automatic hotel, meal and gap searches do not send Google your raw itinerary lines, raw hotel text, travel dates, reservation notes, airport details or completed schedule.</p>
        <p>Google may return public listing fields such as names, coordinates, opening periods, ratings, review counts, photos and Google Maps links. Food and gap-fill suggestions stay in page memory and are never automatically accepted: they are recalculated as ordinary itinerary items only after you explicitly choose one. If you leave the hotel unspecified and ask TripCheck to recommend a base, the leading hotel candidate may be used as a provisional planning base and remains replaceable.</p>
        <p>These paid-provider endpoints require same-origin requests, apply individual hotel, food and route feature kill switches, set no-store response controls and reserve bounded request, anonymous-session, trip, day and month quotas before provider access. Production requests fail closed when the durable quota store is unavailable. The quota ledger contains only opaque subject hashes plus provider, operation, scope, time bucket and counts; it does not contain itinerary, place, hotel, date or reservation content.</p>
        <p>When Rakuten Travel integration is configured, TripCheck may also send only the hotel-search anchor coordinates to Rakuten Web Service. Rakuten may return nearby property names, coordinates, a reference minimum charge, review score, review count and a Rakuten Travel page URL. TripCheck attaches these facts only to a clearly matching Google-listed property and links the displayed Rakuten information back to Rakuten Travel. It does not send your itinerary text, travel dates, airport details or completed schedule to Rakuten.</p>
        <p>Google evidence is ranked and converted into schedule constraints by deterministic code. Structured opening periods are checked against each travel date; flexible places may move to an open day, and a place with no usable verified window is left out and disclosed. TripCheck does not send your full itinerary, dates, reservation notes, airport details or completed schedule to an AI.</p>
        <p>Selecting a stop can automatically load its current Google listing in the detail panel. For meal candidates discovered beside the active day&apos;s route, TripCheck may send only the supplied candidate names, public addresses, place types, meal period and area to Anthropic, which writes compact comparison labels for those candidates. For the shortlisted hotel candidates it may also send their names, bounded areas, Google rating and review counts, planner-computed travel minutes and style or price hints to Anthropic, which may run up to three web searches to check recent reputation before writing its comparison notes. In both cases deterministic TripCheck code chooses the recommended order and the recommended base among the shortlisted candidates; the AI only writes short explanation labels for the supplied candidates; the AI cannot add a restaurant or invent ratings, opening hours, prices or menu facts, and every displayed fact stays Google-owned. TripCheck sends a resolved place, restaurant or hotel name, its public address or area, interface language and search purpose to Anthropic&apos;s web-search tool only when you request recent public-source context or explicitly refresh an eligible result. It does not automatically run public-web searches for every place in a new plan. Anthropic may search indexed public sources such as X, Instagram, local news and firsthand blogs. TripCheck accepts only source URLs actually returned by the search, shows factual notes only when a cited excerpt is available, rejects sources verifiably older than 90 days and labels unknown dates instead of presenting them as recent. A quick check is capped at one search and this optional enrichment never blocks access to the core itinerary.</p>
        <p>Results are held in page memory and are not written to a TripCheck database. To prevent duplicate charges, the public-web result may remain in server memory for up to 30 minutes. If AI search is unavailable or slow, the Google listing and rule-based checks remain usable. Anthropic processes the search under the <a href="https://www.anthropic.com/legal/privacy" rel="noreferrer" target="_blank">Anthropic Privacy Policy</a>.</p>
      </section>
      <section>
        <h2>Device storage</h2>
        <p>TripCheck stores your interface language and up to ten recently generated plans in this browser. Plans use IndexedDB when it is available and fall back to non-persistent in-memory storage when private-mode or browser restrictions prevent it. A saved entry contains the user-authored inputs and edits needed to reopen that plan. If you explicitly choose one ambiguous Google match, it may also contain only that stable Google Place ID so TripCheck can request the current listing again; it does not save Google&apos;s display name, address, hours, reviews, photos, route response or other variable provider content. A manual pin retains only the name, address and coordinates you entered. You can remove each recent plan from the planner, and clearing this site&apos;s browser data removes all persistent copies.</p>
        <p>If you enter your passport expiry date for the validity check, it is kept only in this browser&apos;s local storage and is never sent to TripCheck or any provider — the comparison against the destination&apos;s validity rule happens entirely on this device. Clearing the field or this site&apos;s browser data removes it.</p>
      </section>
      <section>
        <h2>Share links</h2>
        <p>When you choose to copy a share link, the same form inputs, explicit Place-ID choices and any traveller-authored manual pins are encoded in the URL fragment after the # symbol. Browsers do not send that fragment to TripCheck when opening the page, and TripCheck does not store the link. Anyone who receives the complete link can read and rebuild the shared trip, so treat it as containing your itinerary and do not share it more broadly than intended.</p>
      </section>
      <section>
        <h2>Operational data</h2>
        <p>TripCheck records a small, enumerated set of aggregate funnel events so it can measure whether the planner works and control provider cost. Allowed fields are limited to counts, elapsed solver time, result state, provider/error category and the type of alternative applied. These events contain no itinerary text, place or hotel name, address, exact date, reservation detail, Place ID or stable user identifier. Unknown fields and free text are rejected by the event endpoint.</p>
        <p>Normal hosting and logging infrastructure may process an IP address, request time and basic request metadata to deliver and protect the service. TripCheck does not intentionally place itinerary content in analytics or application logs. Operational log retention follows the configured hosting provider retention period and must be reviewed before production release.</p>
      </section>
      <section>
        <h2>Contact and changes</h2>
        <p>This early product does not yet create user accounts or process payments. The policy will be updated before introducing server-saved trips or any AI processing of full itinerary text.</p>
      </section>
      <footer><Link href="/">← Return to TripCheck</Link><Link href="/terms">Terms of use →</Link></footer>
    </main>
  );
}
